security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: identifiant
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    encoders:
        App\Entity\User: plaintext

    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/ roles: ROLE_ADMIN }
    - { path: ^/system roles: ROLE_USER }
