security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: identifiant
    firewalls:

              dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
        login:
            pattern: ^/login$
            security: false

    encoders:
        App\Entity\User:
            algorithm: sha512
            iterations: 9616
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin ,roles: ROLE__SUPER_ADMIN }
    - { path: ^/admin/system, roles: ROLE_ADMIN }
    
