security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: identifiant
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
        login:
            pattern: ^/login$
            security: false

    encoders:
        App\Entity\User:
            algorithm: sha512
            iterations: 9616
            encode_as_base64: true

    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/system/consultation/cron/linux/4530945389, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/system ,roles: ROLE_ADMIN }
    - { path: ^/admin ,roles: ROLE_SUPERADMIN }
    - { path: ^/user ,roles: ROLE_SUPERADMIN }
    - { path: ^/entreprise ,roles: ROLE_SUPERADMIN }
