swiftmailer:
    transport:            smtp
    username:             noreply@nexus-creation.com
    password:             noreply60
    host:                 ssl0.ovh.net
    port:                 465
    encryption:           ssl
    auth_mode:            ~
    spool:
        type:                 file
        path:                 "%kernel.cache_dir%/swiftmailer/spool"
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_addresses:   []
    disable_delivery:     ~
    logging:              "%kernel.debug%"
