#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Connexion
#     path: /
#     controller : App\Controller\DefaultController


app_lucky_number:
    path: /user
    controller: App\Controller\UserController::index